### ISSUE TITLE
楼主找工作吗？

### ISSUE THREAD

**Issue by vcbeaut** [huanghuidmml/tfbert#2]
来我这儿，杠杠滴

**Comment by HuiResearch** [comment]
> 来我这儿，杠杠滴

还在继续读书，等以后找工作的时候希望你还招我，哈哈

**Comment by vcbeaut** [comment]
> > 来我这儿，杠杠滴
> 
> 还在继续读书，等以后找工作的时候希望你还招我，哈哈

楼主方便加我微信吗？也有实习机会的。vx: vcbeaut
